---

- name: Explore
  hosts: rnodes
  become: yes
  vars_files:
    - priv/vault1.yml
  tasks:
    - name: ping
      ping:
    - name: Explore Disks
      shell: df -h
      register: disk_usage
    - name: Show disk info
      debug: msg="{{ disk_usage.stdout_lines }}"
    - name: Get packages
      shell: dpkg-query -f '${binary:Package}\n' -W
      register: packages
    - name: Print packages
      debug: msg="{{ packages.stdout_lines }}"
