---

- name: Explore
  hosts: rnodes
  become: yes
  vars_files:
    - priv/vault1.yml
  tasks:
    - name: ping
      ping:

    - name: Show hardware info
      block:
        - debug: msg="total RAM is {{ ansible_memory_mb.real.total }} MB"
        - debug: var=ansible_mounts
        - debug: var=ansible_processor_cores
        - debug: var=ansible_processor
    - name: Ensure sufficient RAM
      fail: msg="not enough RAM - 32GB needed"
      when: ansible_memory_mb.real.total < 32000

    - name: Show OS info
      block:
        - debug: var=ansible_distribution
        - debug: var=ansible_distribution_version
    - name: Get packages
      shell: dpkg-query -f '${binary:Package}\n' -W
      register: packages
    - name: Print packages
      debug: var=packages.stdout_lines

